### ISSUE TITLE
FWHM Calculations Return Error When Distance Not Provided

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#13]
If distance is None, "beamwidth_phys" used in the FWHM calculation does not exist. We can fix this when we figure out how to store fitting results today

**Comment by hopehhchen** [comment]
Sorry!  It's actually mostly due to wrong indentation levels.  I have fixed it and made it compatible with the situation when there is no header and everything is calculated in pixel units (dcf2d79c02d106efda3c0c6e92f3df607a03e99c).  But you are right.  The current way to store FWHMs is not optimal, and should be reconsidered when we modify how the results are stored.

**Comment by catherinezucker** [comment]
Thanks!
