### ISSUE TITLE
Storing results...

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#16]
I'm starting to think that we have too many nested dictionaries when storing results. For instance, when someone wants to find the median cut across the mask, they have to do this:

    print(np.median(fil._results['build_profile']['dictionary_cuts']['mask_width']))

Which seems overly complicated. @hopehhchen Is there anyway we can simplify this and make it easier on the user? Or do you think it is OK as is?

**Comment by hopehhchen** [comment]
@catherinezucker, that's why they are all stored under this slightly weird property name, `self._results`.  The style guideline of Python suggests that feature names with a single leading underscore should be used for "internal indicators," meaning that these feature names are not the primary feature names that the users would access (and we can skip them in the documentation as well).  See [this discussion on Stackoverflow](https://stackoverflow.com/questions/14671487/what-is-the-difference-in-python-attributes-with-underscore-in-front-and-back).

On the other hand, as you can see in the code, users can access results stored in `self._results` under the feature names that are identical to the keywords in the (nested) dictionary.  In your example, you can actually access the cuts by calling `self.dictionary_cuts`.  Thus, your code can be:

```
print(np.median(fil.dictionary_cuts['mask_width']))
```

which is hopefully simple enough.  There's only one exception, which are the FWHM parameters we added the other day.  I'll fix it and have them stored under `self.FWHM` or similar names.

Do you think it makes sense?  We can try to make it even simpler if you want.

**Comment by catherinezucker** [comment]
No, that makes sense! I didn't know you could access both ways... I think we should keep it like it is. Thanks :)

**Comment by hopehhchen** [comment]
FWHMs are cleaned up and stored under the property names, `self.FWHM` and `self.FWHM_deconv`.  See ff809fa4d28e757de60cbdf428116af0bade7834.
