### ISSUE TITLE
Store cuts out to a chosen radius

### ISSUE THREAD

**Issue by hopehhchen** [catherinezucker/radfil#5]
This was in the original code (see the master branch).  HC will add it back in.

**Comment by hopehhchen** [comment]
I have added `profile_edge` in the `build_profile` feature.  The parameter will decide the largest radial distance to mask and store the profile in `dictionary_cuts` under the key `profile_masked`.  The original (before masking) is kept under `profile`.  See 201a0bf18b4cd306090cd64c4426c405d510810a.

@catherinezucker, I don't quite see the reason why we should mask the profile that is stored in `dictionary_cuts`.  The masking seems redundant to me, with `bgdist` and `fitdist` in the `fit_profile` feature.  If it is only for plotting, I can adjust `xlim` (along the axis of radial distance) in the plotter.  What do you think?

**Comment by catherinezucker** [comment]
Yeah, I agree! The only reason I suggested it was because when I was building the profile for one of my filaments dictionary_cuts wasn't storing anything beyond a pc, so I was confused where the rest of the profile went. Did dictionary cuts always store everything? If so it might have been user error on my part. Anyways, thanks again :)

**Comment by hopehhchen** [comment]
Then there must be a bug somewhere, since it should always store the cuts all the way to the mask edge, and its behavior should be independent of `bgdist` or `fitdist` (or the newly added `profile_edge`).   I'll go through the codes again.  Otherwise, maybe you can show me the case where the unexpected happens on Monday.  Thanks! :)

**Comment by catherinezucker** [comment]
Sorry @hopehhchen --- I read this wrong, and I think we are on different wavelengths. The code needs to store cuts beyond the mask edge. When you said you stored all the cuts, I thought you meant you stored all the cuts from one side of the image to the other, not just within the mask. In order for any of the fits to be legitimate, we need to fit the profile out to at least a parsec or two, so *every* cut needs to go out a pc, even if that is outside the filament mask. Same with the background subtraction. For my filaments  I need to estimate the background at least 3+ pc outside the spine (essentially the flattening radius), so it needs to build and store the cuts even outside the filament masks. That was the purpose of "cutdist" in the original code. I would build out a cut from one side of the image to the other and then cut it down to the preferred distance of the user, so it essentially determined how far out beyond the mask to store the cuts. There is of course an issue that far away from the spine certain pixels might lie in more than one cut, but this is definitely preferable to only using the cuts inside the mask itself to do the fitting. How hard will it be to change the code to build out the profiles to cutdist? Right now it breaks when I input profile_edge or bgdist beyond the mask_width. So for Musca for example, the median mask_width is only 0.3 pc (and the cuts are only saved out to ~0.45 pc), but when I do any of the fitting or background subtraction I need to have the full profile like I do in the original tutorial, where I estimated the background between 1-2 pc. Otherwise our background subtraction values will be totally wrong. Hopefully that makes sense? We can talk about it more tomorrow :)

**Comment by hopehhchen** [comment]
Hey, @catherinezucker, thanks for going over this with me again.  I'll repeat what I understand:

1. The full profiles of cuts, from one side to the other of the original image (but within some `cutdist` from the spine), need to be stored and used in background/profile fitting, of which the ranges are in turn determined by `bgdist` and `fitdist`.
2. The mask is only used to find the spine.

If this is what you have in your mind, then the answer to your second question is: No, it will not take a lot of effort to change the code.  All I need to do is to use the unmasked image as the input to `profile_tools.profile_builder`, and I think I can try implementing it before our meeting on Monday so we may check whether the outcome is what you want.

I think this procedure makes sense, but let's talk about it more tomorrow so to make sure that no bias would come out of this.  Thanks for explaining this to me again! :)

**Comment by catherinezucker** [comment]
Yes, @hopehhchen ! That's exactly what I have in mind! And I don't think we should
get rid of the option to only look at the cuts inside the mask_width
(exactly what you have now) because I think some people will absolutely use
it. I just think we need to add the option to store cuts beyond the mask
width if the user requests it. This goes back to the argument of what
exactly is a valid fitting distance, and how this affects your physical
conclusions on the widths. If the width of the mask does not correspond to
the flattening radius of the profile, your background subtraction will be
much too high, and you'll only be fitting the innermost portion of the
Gaussian--and we know that doing that gives you a fundamentally different
width then if you fit to the flattening radius. The other thing to consider
is that sometimes the spine of the filament is offset from the center of
the mask (in the case of cores for example) and so you would ideally want
to measure out X pc from either side of the maximum column density point,
and not from the original spine center, to get a true estimate of the width
in that region. So in cases of "shift=True" the dictionary_cuts would need
to store radial cuts out to cutdist from the maximum column density point
and not from the spine center (if they're different). And yes, we should
definitely discuss potential biases tomorrow! Also happy to do some code
development then, if you want to wait until the meeting to implement. Might
be easier in person anyways???

Thanks again for everything!

**Comment by hopehhchen** [comment]
This is done.  The issue can be closed after the fitting is tested to be stable (#9).
